[tool.poetry]
name = "pyodide-demo"
version = "0.1.0"
description = ""
authors = ["Steven Jin <t-sjinxuan@microsoft.com>"]

[tool.poetry.dependencies]
python = "^3.8"
azure-ai-textanalytics = "^5.1.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
ipykernel = "^6.14.0"
pylint = "^2.14.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
